global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-service:8080"]

  - job_name: "location-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["location-service:8082"]

  - job_name: "chat-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["chat-service:8083"]

  - job_name: "alert-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["alert-service:8084"]
