apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: pulseboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: pulseboard-auth-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15

          env:
            - name: DB_URL
              value: jdbc:mysql://mysql:3306/pulseboard

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: pulseboard
spec:
  selector:
    app: auth-service
  ports:
    - port: 8080
      targetPort: 8080
