apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pulseboard
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      - job_name: "auth-service"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["auth-service:8080"]

      - job_name: "location-service"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["location-service:8082"]

      - job_name: "chat-service"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["chat-service:8083"]

      - job_name: "alert-service"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets: ["alert-service:8084"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: pulseboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.5.0
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: pulseboard
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
